# .github/labels.yml

# Issue Types
- name: "type: feature"
  color: "1d76db"
  description: "New feature or enhancement"

- name: "type: bug"
  color: "d73a4a"
  description: "Bug or defect that needs fixing"

- name: "type: docs"
  color: "cccccc"
  description: "Changes related to documentation"

- name: "type: question"
  color: "5319e7"
  description: "A question or request for clarification"

# Critical Production Labels
- name: "critical"
  color: "ff0000"
  description: "🔥 Critical production issue requiring urgent attention"
