arb-dir: lib/l10n
template-arb-file: lib_en.arb
output-localization-file: lib_localization.dart   # 修改產生檔案名稱
output-class: LibLocalization                   # 修改類別名稱
synthetic-package: false
nullable-getter: false