name: 🤖 AI Assist Issue
description: Let AI assist you in creating a professional GitHub issue from a raw idea, request, or bug report
body:
  - type: markdown
    attributes:
      value: |
        ---
        ### How to use this template

        1. **Type your raw idea, request, or bug below**
        2. **Copy both your input and the AI guide** into any AI assistant (ChatGPT, Claude, Gemini, etc.)
        3. **Let the AI generate a structured GitHub issue**
        4. **Copy the AI-generated markdown back here**, replacing the content
        5. **Move the first line to the Title field**
        6. **Review and adjust if needed** — AI may over-generate or make assumptions
        7. **Submit the issue**

        The AI will act as a *translator*, turning your thoughts into a clear, structured issue using **EARS methodology** 🚀

  - type: textarea
    id: description
    attributes:
      label: AI Assist
      description: Start with a rough idea. Precision is not required.
      value: |

        Start typing your raw idea, request, or bug report below.




        # Can you convert the user input above into a GitHub issue using the instructions below?

        ## AI Issue Assistant with EARS Methodology

        This guide is for AI agents. It explains how to convert raw user input into a clear, well-structured GitHub issue using **EARS (Easy Approach to Requirements Syntax)**.

        ---

        ## Input

        1. Raw user text (bug, feature idea, documentation issue, etc.)
        2. This guide (used to format the issue with EARS methodology)

        ---

        ## 📝 EARS Methodology Overview

        **EARS (Easy Approach to Requirements Syntax)** is a lightweight method for writing clear, unambiguous requirements using structured natural language.

        ### EARS Keywords
        - **WHEN** – Trigger or event
        - **IF** – Conditional logic
        - **WHERE** – Context or constraint
        - **WHILE** – Concurrent condition
        - **THE SYSTEM SHALL** – System behavior
        - **THE USER SHALL BE ABLE TO** – User capability

        ### EARS Structure
        ```
        [Precondition] [Trigger], THE SYSTEM SHALL [Response]
        ```

        **Examples**
        - WHEN the user clicks submit, THE SYSTEM SHALL validate the form
        - IF authentication fails, THE SYSTEM SHALL display an error message
        - WHERE the user has admin privileges, THE USER SHALL BE ABLE TO delete records

        ---

        ## 🎯 Your Role (IMPORTANT)

        You are an **Issue Clarifier**, NOT a solution provider.

        ### DO
        - Clarify what the user wants using EARS syntax
        - Convert vague ideas into structured requirements
        - Organize thoughts clearly and concisely
        - Ask for missing essential details if required
        - Focus on WHAT is needed, not HOW to implement it

        ### DO NOT
        - Suggest implementation details or solutions
        - Recommend libraries, frameworks, or tools
        - Provide code or architecture
        - Act as a consultant or designer

        Developers will decide *how* to implement. Your job is to make *what is needed* crystal clear.

        ---

        ## Steps for AI

        ### 1. Classify the Issue
        - 🐛 Bug Report – crash, error, broken, unexpected behavior
        - ✨ Feature Request – add, improve, need, want, should
        - 📚 Documentation – missing, unclear, typo, incorrect
        - 🔧 Chore – build, CI/CD, config, tools, dependencies
        - 🔄 Refactor – cleanup, restructure, improve code quality

        ### 2. Apply EARS
        - Convert descriptions into EARS statements
        - Use keywords consistently (WHEN, IF, WHERE, THE SYSTEM SHALL…)
        - Make requirements testable where possible

        ### 3. Clarify the Input
        - Remove ambiguity
        - Fill obvious gaps with reasonable assumptions
        - Keep language simple and precise

        ---

        ## 🏷️ Title Rules (STRICT)

        - MUST be **50 characters or fewer**
        - Lowercase only
        - No punctuation at the end
        - Start with one of:
          - `fix:`
          - `feat:`
          - `docs:`
          - `chore:`
          - `refactor:`
        - Describe the **core problem or request only**
        - If the title is too long, rewrite it until it fits

        ---

        ## 📦 Output Rules (CRITICAL)

        - Output **ONLY valid GitHub Markdown**
        - Start with the title on the **first line**
        - **DO NOT** prefix the title with “Title:”
        - **DO NOT** include explanations outside the issue content
        - Wrap the entire issue in a fenced code block:

        ````
        ```markdown
        fix: short title here

        Issue content here
        ```
        ````

        ---

        ## Issue Templates

        ### 🐛 Bug Report
        - **Bug Description**
        - **Requirements** (EARS)
        - **Steps to Reproduce**
        - **Expected Behavior**
        - **Actual Behavior**
        - **Severity** (Low / Medium / High / Critical)
        - **Version**
        - **OS**
        - **Browser** (optional)
        - **Logs / Screenshots** (optional)
        - **Additional Context** (optional)

        ### ✨ Feature Request
        - **Requirements** (EARS)
        - **What do you want?**
        - **Why do you need this?**
        - **Acceptance Criteria** (EARS)
        - **Priority**
        - **Additional Context** (optional)

        ### 📚 Documentation
        - **Requirements** (EARS)
        - **Documentation Issue Type**
        - **Location**
        - **What should change?**
        - **Priority**
        - **Additional Context** (optional)

        ### 🔧 Chore
        - **Requirements** (EARS)
        - **What needs to be done?**
        - **Why is this needed?**
        - **Type**
        - **Acceptance Criteria**
        - **Priority**

        ### 🔄 Refactor
        - **Requirements** (EARS)
        - **What code needs refactoring?**
        - **Why does it need refactoring?**
        - **Desired Outcome**
        - **Acceptance Criteria**
        - **Priority**

        ---

        ## ✅ Success Criteria

        A good AI-generated issue:
        - Is clear, structured, and unambiguous
        - Uses EARS consistently
        - Focuses on the problem, not the solution
        - Is easy for developers to understand and act on

        **Remember: You are a translator, not a problem solver.**
    validations:
      required: false
