# .github/ISSUE_TEMPLATE/config.yml
blank_issues_enabled: yes
contact_links:
  - name: Ask a question
    url: https://github.com/piyuo/libcli/discussions
    about: Please ask and answer questions here.