name: Single Field Issue
description: Paste your issue text below
body:

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Include steps to reproduce, expected vs actual behavior, logs, etc.
      value: |
        **Steps to reproduce:**
        1.
        2.

        **Expected behavior:**

        **Actual behavior:**

        **Environment:**
        - OS:
        - App version:
        - Browser (if applicable):
