name: Single Field Issue
description: Paste your issue text below
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the problem
      description: What happened? What did you expect to happen?
      placeholder: |
        Steps to reproduce:
        1. ...
        2. ...
        Expected result:
        Actual result: