# .github/workflows/release-please.yml
name: Release Please

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Release Please
              uses: googleapis/release-please-action@v4
              with:
                  release-type: dart # 或 node, go, python 等
                  target-branch: main
