# .github/workflows/release-please.yml
name: Release Please

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Release Please
              uses: googleapis/release-please-action@v4
              with:
                  config-file: .release-please-config.json
